export const config = {
  MINIO_ENDPOINT: '10.128.0.5',
  MINIO_PORT: 8006,
  MINIO_ACCESS_KEY: 'y5ZDcs6hJhUsdZj5PkNI',
  MINIO_SECRET_KEY: 'zL9Rc8WJpAUkzR846OXRleyDTbC66oDIYIwOJDXu',
  MINIO_BUCKET_NAME: 'picture',
};
